# Generated by Django 4.1.1 on 2022-09-24 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='certificate',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_ratings',
            field=models.FloatField(default='0.0', max_length=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_votes',
            field=models.CharField(default='0', max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='NA', max_length=5000),
        ),
        migrations.AddField(
            model_name='movie',
            name='released_year',
            field=models.CharField(default='NA', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default='0', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.CharField(default='0.0', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.CharField(default='NA', max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.CharField(default='0.0', max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.FileField(default='NA', max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='myrating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
